version: 2
formats: []

build:
  os: ubuntu-20.04

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# python:
#     version: 3.7
#     install:
#         - requirements: docs/requirements.txt

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
